// Retro 8-bit color palette for terminal theme
export const RETRO_COLORS = {
  // Primary colors
  MATRIX_GREEN: "#00ff41",
  BRIGHT_YELLOW: "#ffff00",
  CYAN: "#00ffff",
  MAGENTA: "#ff00ff",
  ORANGE: "#ff5500",
  WHITE: "#ffffff",

  // Secondary colors
  PINK: "#ff0080",
  MINT_GREEN: "#00ff80",
  LIME_GREEN: "#80ff00",
  LIGHT_YELLOW: "#ffff80",

  // Background colors
  DARK_BG: "#1a1a2e",
  BORDER_COLOR: "#16213e",
  BLACK: "#000000",
} as const;

// Vibrant Retro Pixel Color Palette (from user's color grid)
export const VIBRANT_RETRO_COLORS = {
  // Row 1 - Reds/Oranges/Yellows
  HOT_PINK: "#FF4D6D",
  CORAL: "#FF8C42",
  ORANGE_YELLOW: "#FFB347",
  GOLD: "#FFD700",
  BRIGHT_YELLOW: "#FFFF00",

  // Row 2 - Purples/Pinks
  PURPLE: "#9D4EDD",
  MAGENTA_PINK: "#E83F6F",
  PINK: "#FF6B9D",
  SALMON: "#FF8E72",
  ORANGE: "#FFA647",

  // Row 3 - Blues/Purples/Pinks
  BLUE: "#5A4FCF",
  LAVENDER: "#B388FF",
  BABY_PINK: "#FF9FF3",
  LIGHT_PINK: "#FFC8DD",
  PEACH: "#FFE5D9",

  // Row 4 - Blues/Teals/Mints
  PERIWINKLE: "#8B8CFF",
  CYAN: "#00D9FF",
  TEAL: "#00F5D4",
  MINT: "#A0FFB0",
  LIME: "#D4FF9E",

  // Row 5 - Greens/Blues
  SKY_BLUE: "#00A8E8",
  EMERALD: "#00D68F",
  LIME_GREEN: "#4DFF00",
  BRIGHT_LIME: "#ADFF02",
  YELLOW_GREEN: "#D9FF00",
} as const;

// Color array for cycling through in graphs
export const VIBRANT_COLOR_ARRAY = [
  VIBRANT_RETRO_COLORS.HOT_PINK,
  VIBRANT_RETRO_COLORS.CORAL,
  VIBRANT_RETRO_COLORS.ORANGE_YELLOW,
  VIBRANT_RETRO_COLORS.GOLD,
  VIBRANT_RETRO_COLORS.BRIGHT_YELLOW,
  VIBRANT_RETRO_COLORS.PURPLE,
  VIBRANT_RETRO_COLORS.MAGENTA_PINK,
  VIBRANT_RETRO_COLORS.PINK,
  VIBRANT_RETRO_COLORS.SALMON,
  VIBRANT_RETRO_COLORS.ORANGE,
  VIBRANT_RETRO_COLORS.BLUE,
  VIBRANT_RETRO_COLORS.LAVENDER,
  VIBRANT_RETRO_COLORS.BABY_PINK,
  VIBRANT_RETRO_COLORS.LIGHT_PINK,
  VIBRANT_RETRO_COLORS.PEACH,
  VIBRANT_RETRO_COLORS.PERIWINKLE,
  VIBRANT_RETRO_COLORS.CYAN,
  VIBRANT_RETRO_COLORS.TEAL,
  VIBRANT_RETRO_COLORS.MINT,
  VIBRANT_RETRO_COLORS.LIME,
  VIBRANT_RETRO_COLORS.SKY_BLUE,
  VIBRANT_RETRO_COLORS.EMERALD,
  VIBRANT_RETRO_COLORS.LIME_GREEN,
  VIBRANT_RETRO_COLORS.BRIGHT_LIME,
  VIBRANT_RETRO_COLORS.YELLOW_GREEN,
] as const;

// Language color mappings
export const LANGUAGE_COLORS = {
  TypeScript: RETRO_COLORS.MATRIX_GREEN,
  JavaScript: RETRO_COLORS.BRIGHT_YELLOW,
  Python: RETRO_COLORS.CYAN,
  HTML: RETRO_COLORS.ORANGE,
  CSS: RETRO_COLORS.MAGENTA,
  Shell: RETRO_COLORS.WHITE,
  Go: RETRO_COLORS.LIME_GREEN,
  "C++": RETRO_COLORS.MINT_GREEN,
  Lua: RETRO_COLORS.PINK,
  Other: RETRO_COLORS.WHITE,
} as const;

// Repository color palette for variety
export const REPO_COLORS = [
  RETRO_COLORS.CYAN,
  RETRO_COLORS.BRIGHT_YELLOW,
  RETRO_COLORS.MATRIX_GREEN,
  RETRO_COLORS.MAGENTA,
  RETRO_COLORS.ORANGE,
  RETRO_COLORS.WHITE,
  RETRO_COLORS.LIME_GREEN,
  RETRO_COLORS.PINK,
  RETRO_COLORS.MINT_GREEN,
  RETRO_COLORS.LIGHT_YELLOW,
] as const;
